### ISSUE TITLE
Odometry massively jumping numbers

### ISSUE THREAD

**Issue by cland29** [maverick-boiler-robotics-team-4272/2024Bot#5]
## What you expected to see
When the robot is on the field, its odometry should only be minorly diverging due to slip, and hardly moving if the robot isn't moving
## What you saw instead
The robot's pose is massively jumping locations in fractions of seconds. It's significantly harder to notice when the limelight is targeting with April tags, because it quickly "fixes" itself. Without April tags, it can become a massive build-up over time.

## Steps to reproduce
Get a position with Apriltags, then cover them. Drive the robot around while graphing both the Odometry position and the X-axis of the location it should be in.

**Comment by cland29** [comment]
Started reviewing log data from Log_24-02-25_16-10-51. 
Found interesting data to review at time stamp 660.
At 660, the position is 20.74 meters. 
At 660.1924, it jumps to 167.22 meters. 
At 660.2125, it increases to 316 meters
Finally, 660.3925 it increases to 470 meters.

Trying to look at other data around there to see why this occurred.

**Comment by cland29** [comment]
![image](https://github.com/maverick-boiler-robotics-team-4272/2024Bot/assets/6444759/9dbe4233-7890-4d5c-83f1-f7ff9dcbdb02)
## Spikes in Motor Position and Angle
There are times when the motor position (mainly for motor3, id 4, back_right_mod) suddenly spikes from pos ~ 49 to 0.0000003, and it's angle spikes from ~-410 to -5. This dramatic of a change isn't really seen other places, so it's doubtful it's a "fast" movement. They seem to correspond to the sudden spikes in position. 
I wonder if there is a chance this is due to a CANBUS issue, since it appears it happens to other module too, motor 3 just happens to be the most common.

It might be a good idea to observe 2023 robot's CANbus utilization and see if it has similar issues.

**Comment by Dannie226** [comment]
We have prevented this issue by two means. One, a check to make sure that the module's position isn't changing too fast, and two, drastically lowering CAN bus utilization. We haven't seen this issue anymore, so, we will assume it is solved
